# Ctrl+F and replace all instaces of ORGANIZATION and WORKFLOW

name: Terraform Module Check

on:
  push:
  pull_request:

jobs:
  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - name: Verify Terraform Version
        run: terraform --version

      - name: Check Terraform Formatting
        id: fmt
        run: terraform fmt -diff -check -no-color -recursive